# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "0 * * * *"}]
  push: {branches: "master"}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # Display most used languages
      # You can ignore some languages and skip some repositories if you want
      - name: Languages plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, lex, gnuplot, php, blade, elixir, go, dart, swift, javascript, PureBasic
          plugin_languages_skipped: lowlighter
          plugins_errors_fatal: yes
          config_timezone: America/Lima
          use_prebuilt_image: master

